insert into product (ID, NAME, DESCRIPTION, VALUE) values (1, 'Spice - Pepper Portions', 'optimizing', 48.85);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (2, 'Cheese - Roquefort Pappillon', 'client-server', 53.04);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (3, 'Peas Snow', 'Phased', 98.49);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (4, 'Salmon - Atlantic, Fresh, Whole', 'holistic', 84.57);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (5, 'Wine - Marlbourough Sauv Blanc', 'Distributed', 51.48);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (6, 'Shrimp - 31/40', 'Face to face', 47.19);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (7, 'Coffee - Flavoured', 'time-frame', 27.35);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (8, 'Mushroom - Porcini, Dry', 'Operative', 38.04);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (9, 'Shrimp - Black Tiger 8 - 12', 'productivity', 56.24);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (10, 'Bar Energy Chocchip', 'interface', 94.92);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (11, 'Asparagus - Mexican', 'coherent', 1.13);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (12, 'Clams - Bay', 'object-oriented', 94.32);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (13, 'Mushroom - White Button', 'Digitized', 69.69);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (14, 'Cheese - Swiss Sliced', 'fresh-thinking', 55.1);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (15, 'Cheese - Swiss Sliced', 'synergy', 91.79);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (16, 'Puree - Guava', 'empowering', 4.33);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (17, 'Sloe Gin - Mcguinness', 'groupware', 6.1);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (18, 'Table Cloth 81x81 Colour', 'methodology', 2.65);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (19, 'Arrowroot', 'installation', 20.83);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (20, 'Beef - Texas Style Burger', 'installation', 74.07);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (21, 'Pepper - Chili Powder', 'clear-thinking', 10.78);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (22, 'Bread - Kimel Stick Poly', 'challenge', 61.96);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (23, 'Jam - Marmalade, Orange', 'core', 73.49);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (24, 'Tarragon - Fresh', 'incremental', 84.06);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (25, 'Ginger - Pickled', 'Managed', 43.83);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (26, 'Turkey - Breast, Double', '6th generation', 39.54);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (27, 'Hummus - Spread', 'User-friendly', 22.65);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (28, 'Waffle Stix', 'Monitored', 39.29);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (29, 'Sea Bass - Fillets', 'fault-tolerant', 22.07);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (30, 'Soap - Hand Soap', 'Automated', 46.3);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (31, 'Food Colouring - Blue', 'client-server', 59.65);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (32, 'Mushrooms - Black, Dried', 'Public-key', 64.97);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (33, 'Bread - Pain Au Liat X12', 'groupware', 24.15);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (34, 'Appetizer - Asian Shrimp Roll', 'Focused', 40.45);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (35, 'Cookie Dough - Oatmeal Rasin', 'analyzer', 66.82);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (36, 'Pork - Backs - Boneless', 'time-frame', 95.33);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (37, 'Wine - Guy Sage Touraine', 'core', 64.69);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (38, 'Pie Shell - 9', 'superstructure', 37.88);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (39, 'Pork - Tenderloin, Fresh', 'contingency', 8.7);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (40, 'Cup Translucent 9 Oz', 'needs-based', 36.36);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (41, 'Pork - Ham, Virginia', 'Profit-focused', 74.79);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (42, 'Steam Pan - Half Size Deep', 'scalable', 57.56);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (43, 'Table Cloth 72x144 White', 'open architecture', 41.61);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (44, 'Soup Knorr Chili With Beans', 'global', 9.88);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (45, 'Clam Nectar', 'zero defect', 26.89);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (46, 'Soup - Knorr, French Onion', 'workforce', 28.02);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (47, 'Yukon Jack', 'intermediate', 42.78);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (48, 'Cookies - Englishbay Wht', 'holistic', 44.48);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (49, 'Ginsing - Fresh', 'Pre-emptive', 40.52);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (50, 'Tuna - Bluefin', 'concept', 75.26);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (51, 'Tofu - Soft', 'full-range', 92.48);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (52, 'Pastry - French Mini Assorted', 'Front-line', 59.43);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (53, 'Curry Powder', 'bandwidth-monitored', 87.18);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (54, 'Cake - Cheese Cake 9 Inch', 'Profound', 34.65);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (55, 'Nestea - Iced Tea', 'groupware', 70.5);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (56, 'Fond - Neutral', 'actuating', 85.85);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (57, 'Cheese - Le Cru Du Clocher', 'Vision-oriented', 84.18);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (58, 'Chevere Logs', 'definition', 52.72);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (59, 'Gatorade - Xfactor Berry', 'adapter', 30.01);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (60, 'Cookie Choc', 'uniform', 24.91);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (61, 'Turkey Tenderloin Frozen', 'approach', 11.75);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (62, 'Fish - Base, Bouillion', 'context-sensitive', 40.47);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (63, 'Wine - Ruffino Chianti', 'Fully-configurable', 5.03);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (64, 'Beer - Tetleys', 'uniform', 35.51);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (65, 'Rum - Dark, Bacardi, Black', 'Realigned', 30.09);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (66, 'Hipnotiq Liquor', 'zero defect', 85.18);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (67, 'Uniform Linen Charge', 'intranet', 53.43);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (68, 'Turnip - White', 'hub', 17.32);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (69, 'Lobster - Baby, Boiled', 'internet solution', 88.3);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (70, 'Liners - Baking Cups', 'full-range', 91.61);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (71, 'Soy Protein', 'data-warehouse', 93.89);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (72, 'Lamb - Loin Chops', 'encoding', 97.11);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (73, 'Bread - Bistro Sour', 'model', 19.35);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (74, 'Cup - 6oz, Foam', 'Universal', 14.16);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (75, 'Squash - Butternut', 'Ergonomic', 28.64);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (76, 'Pastry - Lemon Danish - Mini', 'interface', 19.41);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (77, 'Extract - Raspberry', 'Networked', 8.21);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (78, 'Wine - Rioja Campo Viejo', 'Optional', 61.68);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (79, 'Bread - Multigrain Oval', 'grid-enabled', 84.93);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (80, 'Pasta - Bauletti, Chicken White', 'Graphic Interface', 14.82);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (81, 'Tamarillo', 'even-keeled', 94.57);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (82, 'Arctic Char - Fillets', 'object-oriented', 40.35);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (83, 'Wine - Chardonnay Mondavi', 'national', 28.47);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (84, 'Lettuce - Frisee', 'methodical', 46.16);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (85, 'Soup - Cream Of Potato / Leek', 'uniform', 29.48);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (86, 'Pate Pans Yellow', 'Secured', 78.79);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (87, 'Tilapia - Fillets', 'help-desk', 54.18);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (88, 'Wine - Ice Wine', 'modular', 68.1);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (89, 'Nantucket - Pomegranate Pear', 'architecture', 46.75);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (90, 'Eggplant - Regular', 'framework', 9.21);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (91, 'Bread - Rye', 'emulation', 21.18);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (92, 'Evaporated Milk - Skim', 'info-mediaries', 36.78);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (93, 'Shrimp - Black Tiger 8 - 12', 'challenge', 54.9);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (94, 'Salt - Sea', 'budgetary management', 48.96);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (95, 'Salmon - Smoked, Sliced', 'Object-based', 5.93);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (96, 'Steel Wool', 'middleware', 9.87);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (97, 'Egg - Salad Premix', 'encoding', 88.73);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (98, 'Pepperoni Slices', 'Automated', 42.04);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (99, 'Coffee Guatemala Dark', 'Versatile', 65.86);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (100, 'Pepper - Paprika, Spanish', 'methodology', 66.85);